name: ci

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        env:
          TS_NODE_TRANSPILE_ONLY: '1'
        run: |
          npm run bootstrap
      - name: Run tests
        env:
          TAP_TYPECHECK: '0'
          TAP_TIMEOUT: '0'
          TAP_COLOR: '1'
        run: |
          npm test -ws --color=always -- -Rdot
